"""Emit test token IDs + the host reference vectors as a C header, so the
device output can be diffed against JAX rather than merely 'looking sane'."""
import sys, numpy as np, jax, jax.numpy as jnp
sys.path.insert(0,"/Users/aaronjosserand-austin/Projects/needle")
from needle.model.tokenizer import get_tokenizer
V,D,F,L,H,S = 8192,64,256,2,4,24
z=np.load("student.npz")
# quantise exactly as export.py does, so host ref == what the device holds
ORDER=["emb","pos"]+[f"b{i}.{k}" for i in range(L) for k in ("q","k","v","o","f1","f2","g1","g2")]
Q={}
for n in ORDER:
    a=np.asarray(z[n],np.float32); s=float(np.abs(a).max())/127.0 or 1.0
    Q[n]=(np.clip(np.round(a/s),-127,127).astype(np.int8).astype(np.float32)*s)
p={"emb":jnp.asarray(Q["emb"]),"pos":jnp.asarray(Q["pos"])}
for i in range(L): p[f"b{i}"]={k:jnp.asarray(Q[f"b{i}.{k}"]) for k in ("q","k","v","o","f1","f2","g1","g2")}
def rms(x,g): return g*x*jax.lax.rsqrt(jnp.mean(x**2,-1,keepdims=True)+1e-6)
def encode(p,ids,m):
    x=p["emb"][ids]+p["pos"][None,:ids.shape[1]]; big=-1e9*(1.0-m)[:,None,None,:]
    for i in range(L):
        w=p[f"b{i}"]; h=rms(x,w["g1"]); B,Tn,_=h.shape
        q=(h@w["q"]).reshape(B,Tn,H,D//H).transpose(0,2,1,3)
        k=(h@w["k"]).reshape(B,Tn,H,D//H).transpose(0,2,1,3)
        v=(h@w["v"]).reshape(B,Tn,H,D//H).transpose(0,2,1,3)
        a=jax.nn.softmax(q@k.transpose(0,1,3,2)/np.sqrt(D//H)+big,-1)
        x=x+(a@v).transpose(0,2,1,3).reshape(B,Tn,D)@w["o"]
        x=x+jax.nn.relu(rms(x,w["g2"])@w["f1"])@w["f2"]
    e=(x*m[...,None]).sum(1)/jnp.maximum(m.sum(1,keepdims=True),1e-6)
    return e/(jnp.linalg.norm(e,axis=-1,keepdims=True)+1e-6)
tok=get_tokenizer(V)
TESTS=["turn the kitchen lights on","i am freezing","set pin 13 high"]
ids=np.zeros((len(TESTS),S),np.int32); m=np.zeros((len(TESTS),S),np.float32)
for i,t in enumerate(TESTS):
    e=tok.encode(t)[:S]; ids[i,:len(e)]=e; m[i,:len(e)]=1
ref=np.asarray(encode(p,jnp.asarray(ids),jnp.asarray(m)))
with open("ref_vectors.h","w") as f:
    f.write("/* generated by mkref.py */\n#pragma once\n#include <stdint.h>\n")
    f.write(f"#define REF_N {len(TESTS)}\n#define REF_S {S}\n#define REF_D {D}\n")
    f.write("static const char *ref_text[REF_N] = {%s};\n" % ",".join('"%s"'%t for t in TESTS))
    f.write("static const int16_t ref_ids[REF_N][REF_S] = {\n")
    for r in ids: f.write("  {"+",".join(str(int(x)) for x in r)+"},\n")
    f.write("};\nstatic const uint8_t ref_len[REF_N] = {%s};\n" % ",".join(str(int(x.sum())) for x in m))
    f.write("static const float ref_vec[REF_N][REF_D] = {\n")
    for r in ref: f.write("  {"+",".join("%.6ff"%x for x in r)+"},\n")
    f.write("};\n")
for t,r in zip(TESTS,ref): print(f"  {t:32s} |v|={np.linalg.norm(r):.4f} v[0:4]={np.round(r[:4],4)}")
print("  wrote ref_vectors.h")
