/* generated by export.py - do not edit */
#pragma once
#include <stdint.h>
#define TENC_V 8192
#define TENC_D 64
#define TENC_F 256
#define TENC_L 2
#define TENC_H 4
#define TENC_S 24
#define TENC_BLOB_BYTES 624472
/* tensor order: emb, pos, b0.q, b0.k, b0.v, b0.o, b0.f1, b0.f2, b0.g1, b0.g2, b1.q, b1.k, b1.v, b1.o, b1.f1, b1.f2, b1.g1, b1.g2 */
extern const uint8_t tinyenc_blob[TENC_BLOB_BYTES];
