"""Export the student to a flat int8 blob + C header for ESP-IDF.

Layout (little-endian): magic 'TENC', u16 V,D,F,L,H,S, then per-tensor
[f32 scale][int8 data...] in fixed order. Dequant is w = q * scale.
"""
import struct, numpy as np
z = np.load("student.npz")
V,D,F,L,H,S = 8192,64,256,2,4,24
ORDER = ["emb","pos"] + [f"b{i}.{k}" for i in range(L)
                          for k in ("q","k","v","o","f1","f2","g1","g2")]
buf = bytearray(b"TENC" + struct.pack("<6H", V,D,F,L,H,S))
manifest = []
for name in ORDER:
    a = np.asarray(z[name], np.float32)
    s = float(np.abs(a).max()) / 127.0 or 1.0
    q = np.clip(np.round(a/s), -127, 127).astype(np.int8)
    buf += struct.pack("<f", s) + q.tobytes()
    manifest.append((name, a.shape, q.nbytes))
open("tinyenc.bin","wb").write(buf)
with open("tinyenc_model.h","w") as f:
    f.write("/* generated by export.py - do not edit */\n#pragma once\n#include <stdint.h>\n")
    f.write(f"#define TENC_V {V}\n#define TENC_D {D}\n#define TENC_F {F}\n")
    f.write(f"#define TENC_L {L}\n#define TENC_H {H}\n#define TENC_S {S}\n")
    f.write(f"#define TENC_BLOB_BYTES {len(buf)}\n")
    f.write("/* tensor order: " + ", ".join(n for n,_,_ in manifest) + " */\n")
    f.write("extern const uint8_t tinyenc_blob[TENC_BLOB_BYTES];\n")
print("  %-22s %-14s %s" % ("tensor","shape","bytes"))
for n,sh,b in manifest: print("  %-22s %-14s %d" % (n,str(sh),b))
print()
print(f"  tinyenc.bin        {len(buf):,} bytes  ({len(buf)/1024:.0f} KB)")
print(f"  tinyenc_model.h    C header emitted")
